### ISSUE TITLE
Links at the top navbar don't work

### ISSUE THREAD

**Issue by rlouyang** [frtennis1/d4dFoober#6]
Tried Chrome as well as Edge. I think it's a problem with the html, but not sure how to fix it

**Comment by melissayu01** [comment]
Hmm they work for me thats weird

**Comment by rlouyang** [comment]
For me, it only happens when you try to open in the same tab, not if you open in new tab/window. Also, it's clearly linked correctly, because you can see the correct url pop up at the bottom left.

**Comment by frtennis1** [comment]
Yeah, I think it's a problem with the javascript, cause the HTML looks good, but the link is nevertheless not working properly.

**Comment by rlouyang** [comment]
Figured out that it's the jquery that breaks it. Disabling it makes the links work again, but jquery is obviously kind of necessary.
